Use `importlib_metadata` to read version
This fixes a bug where the `factory` could not be imported on Python 3.7
if `setuptools` wasn't installed (see below). Rather than require
`setuptools` move to using `import-metadata` so that the same approach
is used for Python < 3.8 and Python >= 3.8 (where `importlib.metadata`
is available in the stdlib)

The bug: installing this distribution without `setuptools` results in an
`ImportError` when trying to determine the distribution's version (only
on Python<3.8, above this it uses the builtin `importlib.metadata`):

    $ python --version
    Python 3.7.4
    $ python -m venv .venv
    $ source .venv/bin/activate
    $ pip uninstall --yes --quiet setuptools
    $ pip install --quiet factory-boy
    $ python -c 'import factory'
    Traceback (most recent call last):
      File "/tmp/tmp.qEc9M3LwV5/.venv/lib/python3.7/site-packages/factory/__init__.py", line 74, in <module>
        from importlib.metadata import version
    ModuleNotFoundError: No module named 'importlib.metadata'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/tmp.qEc9M3LwV5/.venv/lib/python3.7/site-packages/factory/__init__.py", line 78, in <module>
        import pkg_resources
    ModuleNotFoundError: No module named 'pkg_resources'

Fixes #990