Install factory_boy in readthedocs build environment
3eb79173eee147ec5cf827d20b1a1caf5aec915e restored the `__version__`
attribute in the `factory` module, and transitioned the documentation to
read the version for it. However, `factory_boy` is missing from
readthedocs build environment. Attempts to read the `__version__`
resulted in:

```
ModuleNotFoundError: No module named 'factory'
```

Refs #676
Fixes #704